image: jangrewe/gitlab-ci-android

stages:
  - build
  - clean

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - echo $KEYSTORE > key.txt
  - base64 -d key.txt > keystore
  - echo "keyPassword=$KEY_PASSWORD" > keystore.properties
  - echo "keyAlias=$KEY_ALIAS" >> keystore.properties
  - echo "aliasPassword=$ALIAS_PASSWORD" >> keystore.properties

build_apk:
  stage: build
  only:
    - develop
  script:
    - export BUILD_NUMBER=$CI_JOB_ID
    - ./gradlew -g /cache/.gradle clean assembleRelease --parallel --stacktrace --no-daemon -x lint
    - cd app/build/outputs/apk/release/
    - export FILENAME=$(ls)
    - echo FILENAME
  artifacts:
    expire_in: 2 days
    paths:
      - app/build/outputs/apk/release/*.apk
      - app/build/intermediates/manifests/full/release/*.xml
  cache:
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/wrapper
      - .gradle/caches

cleanFile:
  stage: clean
  script:
    - rm -f key.txt
    - rm -f keystore